bf16: true
cutoff_len: 2048
dataset: alpaca_rag_code_review_train_data # or none_RAG
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_thinking: true
eval_steps: 500
eval_strategy: steps
finetuning_type: lora
flash_attn: fa2
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 0.0002
logging_steps: 1
lora_alpha: 16
lora_dropout: 0.05
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: ../Meta-Llama-3.1-8B-Instruct
num_train_epochs: 5.0
optim: adamw_torch
output_dir: saves/Llama-3.1-8B-Instruct/lora/train_2025
packing: false
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 500
stage: sft
template: llama3
trust_remote_code: true
val_size: 0.01
warmup_steps: 0
